/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../gen/petstore.validator';
import { ListPetsContext } from '../gen/pets/pets.context';
import { ListPetsQueryParams, ListPetsResponse } from '../gen/pets/pets.zod';

const factory = createFactory();
export const listPetsHandlers = factory.createHandlers(
  zValidator('query', ListPetsQueryParams),
  zValidator('response', ListPetsResponse),
  async (c: ListPetsContext) => {},
);
