/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../gen/petstore.validator';
import { ShowPetByIdContext } from '../gen/pets/pets.context';
import { ShowPetByIdParams, ShowPetByIdResponse } from '../gen/pets/pets.zod';

const factory = createFactory();
export const showPetByIdHandlers = factory.createHandlers(
  zValidator('param', ShowPetByIdParams),
  zValidator('response', ShowPetByIdResponse),
  async (c: ShowPetByIdContext) => {},
);
