/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../gen/petstore.validator';
import { CreatePetsContext } from '../gen/pets/pets.context';
import { CreatePetsBody, CreatePetsResponse } from '../gen/pets/pets.zod';

const factory = createFactory();
export const createPetsHandlers = factory.createHandlers(
  zValidator('json', CreatePetsBody),
  zValidator('response', CreatePetsResponse),
  async (c: CreatePetsContext) => {},
);
